import test from 'node:test';
import assert from 'node:assert/strict';
import {auditHistoricalEligibility} from '../src/historical-eligibility.mjs';
const hash = 'a'.repeat(64), capture = '2026-10-07T12:00:00.000Z';
function observation(id=1, date='2026-10-01') {return {provider:'open-prices',providerRecordId:String(id),sourceUrl:'https://prices.openfoodfacts.org/api/v1/prices/'+id,capturedAt:capture,observedOn:date,validity:'unconfirmed',eligibleAsActiveOffer:false,attribution:'Open Prices / Open Food Facts',license:'ODbL-1.0',raw:{id,date,type:'PRODUCT',location_id:77,location:{id:77,osm_type:'WAY',osm_id:123},product_code:'PRIVATE_CODE',price:'1.99',price_is_discounted:false,discount_type:null,currency:'EUR',proof_id:42,proof:{id:42,url:'https://private.example/receipt'},owner:'PRIVATE_OWNER',product:{code:'PRIVATE_CODE',product_quantity:500,product_quantity_unit:'g'}}};}
function report(observations=[observation()]) {return {auditVersion:1,generatedAt:'2026-10-07T12:01:00.000Z',referenceDateBasis:'Europe/Berlin',queriedWindow:{sinceInclusive:'2026-09-24',referenceDate:'2026-10-07',upperDateFilterApplied:false},limits:{maxPages:3,pageSize:100,maximumRetainedRecords:300},providerTotal:observations.length,truncated:false,query:{lat:51.96236,lon:7.62571,radiusKm:3,observedSince:'2026-09-24'},requests:[{url:'https://prices.openfoodfacts.org/api/v1/prices?lat=51.96236&lon=7.62571&radius_km=3&currency=EUR&size=100&page=1&date__gte=2026-09-24',capturedAt:capture}],attribution:'Open Prices / Open Food Facts',license:'ODbL-1.0',observations};}
function entry(id=1) {return {providerRecordId:String(id),reviewed:true,category:'rice',brand:null,tags:['vegan'],packQuantity:500,unit:'g',basis:'net',depositCents:0,requiresMembership:false,conditionsReviewed:true,sourceEvidenceReviewed:true,priceBasis:'per_pack',priceIsDiscounted:false,discountType:null};}
function review() {return {auditReviewVersion:1,reportSha256:hash,shoppingDate:'2026-10-07',maxAgeDays:14,allowMembership:false,basket:{version:'staples-v1',items:[{id:'rice',category:'rice',quantity:800,unit:'g',basis:'net',brand:null,requiredTags:['vegan']}]},recordReviews:[entry()]};}
const registry={stores:[{id:'shop'}],reviewedProviderLocationMappings:[{provider:'open-prices',providerLocationId:77,storeId:'shop',reviewedOn:'2026-10-07',reviewKind:'manual-public-address-cross-check',officialSourceUrl:'https://shop.example/address',osm:{type:'WAY',id:123,sourceUrl:'https://api.openstreetmap.org/api/0.6/way/123'}}]};
const audit=(r=report(),v=review(),g=registry)=>auditHistoricalEligibility(r,v,g,{reportSha256:hash});
const line=value=>value.branches[0].lines[0];
test('reviewed evidence gives historical coverage without totals or sensitive fields',()=>{const value=audit();assert.equal(line(value).eligibleCount,1);assert.equal(value.rankingEnabled,false);assert.equal(value.currentPriceEligible,false);const json=JSON.stringify(value);for(const secret of ['PRIVATE_CODE','PRIVATE_OWNER','private.example','1.99','proof','raw'])assert.equal(json.includes(secret),false);});
test('missing review is unknown matching evidence',()=>{const v=review();v.recordReviews=[];assert.equal(line(audit(report(),v)).exclusions.unreviewed_product,1);});
test('hash pinning and duplicate/unknown review identifiers reject',()=>{const v=review();v.reportSha256='b'.repeat(64);assert.throws(()=>audit(report(),v),{code:'REPORT_HASH_MISMATCH'});for(const entries of [[entry(),entry()],[entry(999)]]){const r=review();r.recordReviews=entries;assert.throws(()=>audit(report(),r),{code:'INVALID_RECORD_REVIEW'});}});
test('equivalent demands merge before coverage and quantities sum',()=>{const v=review();v.basket.items.push({...v.basket.items[0],id:'rice-2',quantity:200});const result=audit(report(),v);assert.equal(result.mergedLineCount,1);assert.equal(line(result).requestedQuantity,1000);});
test('newer unreviewed evidence suppresses older reviewed evidence',()=>{const r=report([observation(),observation(2,'2026-10-03')]);const result=line(audit(r));assert.equal(result.eligibleCount,0);assert.deepEqual(result.exclusions,{superseded_observation:1,unreviewed_product:1});});
test('same day differing price or deposit conflicts exclude all candidates',()=>{for(const field of ['price','deposit']){const r=report([observation(),observation(2)]),v=review();v.recordReviews.push(entry(2));if(field==='price')r.observations[1].raw.price='1.89';else v.recordReviews[1].depositCents=25;const result=line(audit(r,v));assert.equal(result.eligibleCount,0);assert.equal(result.exclusions.same_day_conflict,2);}});
test('identical same day evidence need not conflict',()=>{const v=review();v.recordReviews.push(entry(2));assert.equal(line(audit(report([observation(),observation(2)]),v)).eligibleCount,2);});
test('dates exclude impossible calendar dates, stale and future observations',()=>{for(const [day,reason] of [['2026-02-30','invalid_observation_date'],['2026-09-01','stale_observation'],['2026-10-08','future_observation']])assert.equal(line(audit(report([observation(1,day)]))).exclusions[reason],1);});
test('exact units, quantity basis, brands and hard constraints gate coverage',()=>{for(const [changes,reason] of [[{unit:'ml'},'unit_mismatch'],[{basis:'drained'},'basis_mismatch'],[{brand:'named-brand'},'brand_mismatch'],[{requiredTags:['organic']},'constraint_mismatch']]){const v=review();Object.assign(v.basket.items[0],changes);assert.equal(line(audit(report(),v)).exclusions[reason],1);}});
test('unknown deposit, unreviewed source and unresolved conditions exclude',()=>{for(const [changes,reason] of [[{depositCents:null},'unknown_deposit'],[{conditionsReviewed:false},'unreviewed_conditions'],[{sourceEvidenceReviewed:false},'unreviewed_source_evidence']]){const v=review();Object.assign(v.recordReviews[0],changes);assert.equal(line(audit(report(),v)).exclusions[reason],1);}});
test('integer cents require exact decimal euros and reviewed pack evidence',()=>{for(const price of ['1.999','1e2',1.005]){const r=report();r.observations[0].raw.price=price;assert.equal(line(audit(r)).exclusions.invalid_eur_price,1);}const r=report();r.observations[0].raw.product.product_quantity=1000;assert.equal(line(audit(r)).exclusions.pack_evidence_mismatch,1);});
test('nested identities and exact branch OSM identity must agree',()=>{for(const mutate of [raw=>raw.product.code='other',raw=>raw.location.id=78,raw=>raw.proof.id=43]){const r=report();mutate(r.observations[0].raw);assert.equal(line(audit(r)).exclusions.identity_mismatch,1);}const r=report();r.observations[0].raw.location.osm_id=456;assert.equal(line(audit(r)).exclusions.branch_evidence_mismatch,1);});
test('loyalty evidence cannot bypass membership review or opt-in',()=>{const r=report();r.observations[0].raw.discount_type='LOYALTY_PROGRAM';r.observations[0].raw.price_is_discounted=true;const initial=review();initial.recordReviews[0].priceIsDiscounted=true;initial.recordReviews[0].discountType='LOYALTY_PROGRAM';assert.equal(line(audit(r,initial)).exclusions.membership_evidence_mismatch,1);const v=initial;v.recordReviews[0].requiresMembership=true;assert.equal(line(audit(r,v)).exclusions.membership_required,1);v.allowMembership=true;assert.equal(line(audit(r,v)).eligibleCount,1);});
test('explicit pack-price assertion required and unfamiliar price-per excluded',()=>{const v=review();delete v.recordReviews[0].priceBasis;assert.throws(()=>audit(report(),v),{code:'INVALID_RECORD_REVIEW'});const r=report();r.observations[0].raw.price_per='KILOGRAM';assert.equal(line(audit(r)).exclusions.unsupported_price_basis,1);});
test('unmapped records remain global exclusions and no branch inferred by name',()=>{const r=report();r.observations[0].raw.location_id=78;r.observations[0].raw.location.id=78;const value=audit(r);assert.equal(value.unmappedRecordCount,1);assert.equal(line(value).candidateCount,0);});

test('same-day unsupported price basis conflicts with otherwise eligible peer',()=>{const r=report([observation(),observation(2)]),v=review();v.recordReviews.push(entry(2));r.observations[1].raw.price_per='KILOGRAM';const result=line(audit(r,v));assert.equal(result.eligibleCount,0);assert.equal(result.exclusions.same_day_conflict,1);assert.equal(result.exclusions.unsupported_price_basis,1);});
test('source review assertion cannot replace absent proof identity',()=>{const r=report();delete r.observations[0].raw.proof_id;delete r.observations[0].raw.proof;assert.equal(line(audit(r)).exclusions.missing_source_evidence,1);});
test('future observation does not mask latest historical as-of candidate',()=>{const r=report([observation(),observation(2,'2026-10-08')]);const result=line(audit(r));assert.equal(result.eligibleCount,1);assert.equal(result.exclusions.future_observation,1);});
test('discount conditions require exact known raw and reviewed evidence',()=>{for(const mutate of [raw=>delete raw.price_is_discounted,raw=>raw.discount_type='UNKNOWN',raw=>{raw.price_is_discounted=true;raw.discount_type='SALE';}]){const r=report();mutate(r.observations[0].raw);assert.equal(line(audit(r)).exclusions.discount_evidence_mismatch,1);}const r=report(),v=review();r.observations[0].raw.price_is_discounted=true;r.observations[0].raw.discount_type='SALE';v.recordReviews[0].priceIsDiscounted=true;v.recordReviews[0].discountType='SALE';assert.equal(line(audit(r,v)).eligibleCount,1);});

test('provider duplicates and non-product observations cannot give independent eligibility',()=>{for(const [changes,reason] of [[{type:'CATEGORY'},'unsupported_record_type'],[{duplicate_of:99},'provider_duplicate']]){const r=report();Object.assign(r.observations[0].raw,changes);assert.equal(line(audit(r)).exclusions[reason],1);}});

test('top-level OSM and nested product relation identities cannot disagree',()=>{for(const mutate of [raw=>raw.location_osm_id=456,raw=>raw.location_osm_type='NODE',raw=>{raw.product_id=1;raw.product.id=2;}]){const r=report();mutate(r.observations[0].raw);assert.equal(line(audit(r)).exclusions.identity_mismatch,1);}});

test('newer invalid identity or non-product record does not suppress valid historical evidence',()=>{for(const mutate of [raw=>raw.product.code='other',raw=>raw.type='CATEGORY']){const r=report([observation(),observation(2,'2026-10-03')]);mutate(r.observations[1].raw);const result=line(audit(r));assert.equal(result.eligibleCount,1);assert.equal(result.exclusions.superseded_observation,undefined);}});
test('malformed same-day peers cannot silently corroborate eligible evidence',()=>{for(const mutate of [raw=>raw.product.code='other',raw=>{delete raw.proof_id;delete raw.proof;},raw=>raw.location.osm_id=456]){const r=report([observation(),observation(2)]),v=review();v.recordReviews.push(entry(2));mutate(r.observations[1].raw);const result=line(audit(r,v));assert.equal(result.eligibleCount,0);assert.equal(result.exclusions.same_day_conflict,1);}});

test('eligible candidate date profile discloses ages across distinct products',()=>{const r=report([observation(),observation(2,'2026-10-03'),observation(3,'2026-10-08')]),v=review();for(const [index,record] of r.observations.entries()){record.raw.product_code='product-'+index;record.raw.product.code=record.raw.product_code;}v.recordReviews.push(entry(2),entry(3));const result=line(audit(r,v));assert.deepEqual(result.eligibleDateProfile,[{observedOn:'2026-10-01',ageDays:6,observationCount:1},{observedOn:'2026-10-03',ageDays:4,observationCount:1}]);assert.equal(result.mixesEligibleObservationDates,true);assert.equal(result.exclusions.future_observation,1);});
test('excluded candidates contribute no eligible date profile',()=>{const v=review();v.recordReviews=[];const result=line(audit(report(),v));assert.deepEqual(result.eligibleDateProfile,[]);assert.equal(result.mixesEligibleObservationDates,false);});
